title: Mathematics Discord Server
description: A place for people to learn and discuss mathematics.
baseurl: ""
url: "https://mathematics.gg/"

defaults:
  - scope:
      path: ""
    values:
      layout: default

locale: en_US

plugins: []